---

name: GitHub Tag Update

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read

jobs:
  actions-tagger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Update tag
        uses: Actions-R-Us/actions-tagger@68b8860d45b8d5a78fc2b0b4c7bb19da085b38c6
        with:
          publish_latest_tag: true
          token: ${{ secrets.GITHUB_TOKEN }}
